# -*- coding: utf-8 -*-
"""Random Forest

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_ZSAMZ5UivhduqP-2YL5PxtTuPmM69YH
"""

from pandas import read_csv
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
from sklearn.ensemble import RandomForestClassifier

file_name='/content/pima-indians-diabetes.data.csv'
names=['preg','plas','pres','skin','test','mass','pedi','age','class']
DataFrame=read_csv(file_name,names=names)
DataFrame.head()

lis=[1,2,3,4,5,7,8,12]
print(lis)

num_trees=100
seed=7
k_fold=KFold(n_splits=10,random_state=seed,shuffle=True)
model=RandomForestClassifier(n_estimators=num_trees,max_features=3)
k_fold

X = DataFrame.drop('class', axis=1)
Y = DataFrame['class']

result = cross_val_score(model, X, Y, cv=k_fold)
print(result.mean())

result=cross_val_score(model,X,Y,cv=k_fold,scoring='accuracy')
print(result.mean())

DataFrame.tail()

